### PR TITLE
Support AI.MODELSET BLOB into 512MB chunks

### PR DESCRIPTION
**Pull request by sazzad16**

### CODE REVIEW

**Comment by sazzad16** [comment]
@gkorland @DvirDukhan @filipecosta90 Can we consider this PR? It may be reused for AI.MODELSTORE.

**Comment by sazzad16** [comment]
@bsbodden

**Comment by DvirDukhan** [comment]
@sazzad16 can you make it work also on modelstore?
also, can we get the chunck size dynamically from the server?

**Comment by sazzad16** [comment]
@DvirDukhan 

> can you make it work also on modelstore?

That's my plan. But how do you mean? Without this PR?

> can we get the chunck size dynamically from the server?

Is there any way to get that from server? Any specific command?

**Pull request closed without merging**
